/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellPengajuanIndexRouteImport } from './routes/_shell.pengajuan.index'
import { Route as ShellPengajuanIdRouteImport } from './routes/_shell.pengajuan.$id'
import { Route as ShellPengajuanBuatRouteImport } from './routes/_shell.pengajuan.buat'
import { Route as ShellPersetujuanIndexRouteImport } from './routes/_shell.persetujuan.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPengajuanIndexRoute = ShellPengajuanIndexRouteImport.update({
  id: '/pengajuan/',
  path: '/pengajuan/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPengajuanIdRoute = ShellPengajuanIdRouteImport.update({
  id: '/pengajuan/$id',
  path: '/pengajuan/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPengajuanBuatRoute = ShellPengajuanBuatRouteImport.update({
  id: '/pengajuan/buat',
  path: '/pengajuan/buat',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPersetujuanIndexRoute = ShellPersetujuanIndexRouteImport.update({
  id: '/persetujuan/',
  path: '/persetujuan/',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/pengajuan/$id': typeof ShellPengajuanIdRoute
  '/pengajuan/buat': typeof ShellPengajuanBuatRoute
  '/pengajuan/': typeof ShellPengajuanIndexRoute
  '/persetujuan/': typeof ShellPersetujuanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/pengajuan/$id': typeof ShellPengajuanIdRoute
  '/pengajuan/buat': typeof ShellPengajuanBuatRoute
  '/pengajuan': typeof ShellPengajuanIndexRoute
  '/persetujuan': typeof ShellPersetujuanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/pengajuan/$id': typeof ShellPengajuanIdRoute
  '/_shell/pengajuan/buat': typeof ShellPengajuanBuatRoute
  '/_shell/pengajuan/': typeof ShellPengajuanIndexRoute
  '/_shell/persetujuan/': typeof ShellPersetujuanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pengajuan/$id'
    | '/pengajuan/buat'
    | '/pengajuan/'
    | '/persetujuan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/pengajuan/$id'
    | '/pengajuan/buat'
    | '/pengajuan'
    | '/persetujuan'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/dashboard'
    | '/_shell/pengajuan/$id'
    | '/_shell/pengajuan/buat'
    | '/_shell/pengajuan/'
    | '/_shell/persetujuan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pengajuan/': {
      id: '/_shell/pengajuan/'
      path: '/pengajuan'
      fullPath: '/pengajuan/'
      preLoaderRoute: typeof ShellPengajuanIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pengajuan/$id': {
      id: '/_shell/pengajuan/$id'
      path: '/pengajuan/$id'
      fullPath: '/pengajuan/$id'
      preLoaderRoute: typeof ShellPengajuanIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pengajuan/buat': {
      id: '/_shell/pengajuan/buat'
      path: '/pengajuan/buat'
      fullPath: '/pengajuan/buat'
      preLoaderRoute: typeof ShellPengajuanBuatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/persetujuan/': {
      id: '/_shell/persetujuan/'
      path: '/persetujuan'
      fullPath: '/persetujuan/'
      preLoaderRoute: typeof ShellPersetujuanIndexRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellPengajuanIdRoute: typeof ShellPengajuanIdRoute
  ShellPengajuanBuatRoute: typeof ShellPengajuanBuatRoute
  ShellPengajuanIndexRoute: typeof ShellPengajuanIndexRoute
  ShellPersetujuanIndexRoute: typeof ShellPersetujuanIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellPengajuanIdRoute: ShellPengajuanIdRoute,
  ShellPengajuanBuatRoute: ShellPengajuanBuatRoute,
  ShellPengajuanIndexRoute: ShellPengajuanIndexRoute,
  ShellPersetujuanIndexRoute: ShellPersetujuanIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
